Addition of 'request a new code' flow
OfqualGovUK/apply-to-provide-expertise-prototype pull request #46
Opened 2022-10-24 10:48 UTC by Nat-A-M

![Screenshot 2022-10-24 at 11 43 40](https://user-images.githubusercontent.com/113040947/197508632-234dae08-75dc-4ab3-bcd4-4f47674a5f11.png)

2022-10-27 09:10 UTC, jesseyuen commented on app/views/account/index.html
> +  <p class="govuk-body">If you already have a GOV.UK account you can <a href="./sign-in" class="govuk-link">sign in</a>.</p>
This anchor should go to a page that looks like this:
https://ova-alpha.london.cloudapps.digital/govuk_account_sign_in

2022-10-27 09:15 UTC, jesseyuen commented on app/views/account/check-your-emails.html
> +      <p class="govuk-body"> <a href="/application/sorry" class="govuk-link">Request a new code</a> if:</p>
This link should go to this file but lets also rename that file to something more logical like `request-code` 

```suggestion
      <p class="govuk-body"> <a href="/account/create-account" class="govuk-link">Request a new code</a> if:</p>
```

2022-10-27 09:19 UTC, jesseyuen commented on app/views/account/you-are-signed-in.html
> +  <p class="govuk-body">We will now ask you a few questions about your work experience and qualifications.</p>
Suggested copy update below! 

We probably also need to consider a scenario here where they have already finished an application and have bene accepted as an expert. In that instance the content might be something like  "Continue to your access you account". 

```suggestion
  <p class="govuk-body">Continue to apply to become to be a subject matter expert.</p>
```

2022-10-27 09:25 UTC, jesseyuen requested changes
Ive added some thing to look at bud :)

2022-10-27 13:03 UTC, Nat-A-M reviewed
Changes have been made

2022-10-28 06:04 UTC, jesseyuen commented on app/views/account/check-your-emails.html
> +      <p class="govuk-body"> <a href="/application/request-code" class="govuk-link">Request a new code</a> if:</p>
This link was broken. Correct path here:

```suggestion
      <p class="govuk-body"> <a href="/account/request-code" class="govuk-link">Request a new code</a> if:</p>
```

2022-10-28 06:05 UTC, jesseyuen commented on app/views/account/index.html
> +  <p class="govuk-body">If you already have a GOV.UK account you can <a href="./sign-in" class="govuk-link">sign in</a>.</p>
Link path update:

```suggestion
  <p class="govuk-body">If you already have a GOV.UK account you can <a href="/account/sign-in" class="govuk-link">sign in</a>.</p>
```

2022-10-28 06:07 UTC, jesseyuen commented on app/views/account/sign-in.html
> +      text: "We'll use this to check if you have a GOV.UK account"
Copy update:

```suggestion
      text: "Enter your email address to sign in."
```

2022-10-31 09:14 UTC, jesseyuen commented on app/views/account/sign-in.html
> +  <h1 class="govuk-heading-l">Enter your email address</h1>
```suggestion
  <h1 class="govuk-heading-l">Sign in with your GOV.UK account</h1>
```

2022-10-31 09:21 UTC, jesseyuen commented
Having a look now!

Looking good bud. A couple of things:

Have you seen the “If you already have a GOV.UK account you can sign in.” flow in the prototype we are copying? There is a password field on one of the screens! I hadn’t seen it yet, my apologies. 🤦‍♂️ I think we should add these screens into our flow. 

Start the flow here: https://ova-alpha.london.cloudapps.digital/govuk_create_or_sign_in

Also, don't forget to update the links here:

![Screenshot 2022-10-31 at 09 20 07](https://user-images.githubusercontent.com/1108991/198974371-96636831-6c2d-4398-9880-98a08cc9faac.png)

2022-11-02 16:34 UTC, jesseyuen approved these changes

2022-11-02 16:35 UTC, jesseyuen approved these changes
Looks good!

2022-11-02 16:51 UTC, merged